name: Deploy folder

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r tutorials deploy/tutorials

      - name: Install Neocities CLI
        run: npm install neocities

      - name: Deploy
        run: ./node_modules/.bin/neocities push deploy
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}