name: Deploy folder

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Neocities CLI (local)
        run: npm install neocities

      - name: Deploy to /tutorials
        run: ./node_modules/.bin/neocities push tutorials --dir tutorials
        env:
          NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}